// Generated by CoffeeScript 1.8.0
(function() {
  var ENEM_END, ENEM_HEAD, ENEM_RES_HEAD, Evernote, MIME_TO_EXTESION_MAPPING, argv, async, creatImportNote, createENEM_RES_END, createEmailNote, createHashHex, createRes, crypto, email, filterImg, fs, fse, limit, mime, noteStore, readImg, shell, sliceImg;

  noteStore = require('./evernote');

  Evernote = require('evernote').Evernote;

  fs = require('fs');

  crypto = require('crypto');

  mime = require('mime');

  async = require('async');

  fse = require('fs-extra');

  email = require('./email');

  argv = require('optimist').argv;

  MIME_TO_EXTESION_MAPPING = {
    'image/png': '.png',
    'image/jpg': '.jpg',
    'image/jpeg': '.jpg',
    'image/gif': '.gif'
  };

  ENEM_HEAD = '<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE en-export SYSTEM "http://xml.evernote.com/pub/evernote-export3.dtd"><en-export export-date="20150420T023922Z" application="Evernote" version="Evernote Mac 6.0.8 (451398)"><note><title>无标题</title><content><![CDATA[<?xml version="1.0" encoding="UTF-8" standalone="no"?><!DOCTYPE en-note SYSTEM "http://xml.evernote.com/pub/enml2.dtd"><en-note>';

  ENEM_END = "</en-note>]]></content><created>20150420T023831Z</created><updated>20150420T023912Z</updated><note-attributes><latitude>22.60284578376065</latitude><longitude>114.0366381790896</longitude><altitude>87.88452911376953</altitude><author>友情</author><source>desktop.mac</source><reminder-order>0</reminder-order></note-attributes>";

  ENEM_RES_HEAD = '<resource><data encoding="base64">';

  createENEM_RES_END = function(res) {
    return "</data><mime>" + res.mime + "</mime><width></width><height></height><duration>0</duration><resource-attributes><file-name>" + res.img + "</file-name></resource-attributes></resource>";
  };

  filterImg = function(limit, cb) {
    if (limit == null) {
      limit = 100;
    }
    return fs.readdir(process.cwd(), function(err, files) {
      var f, imgFiles, type, _i, _len;
      if (err) {
        return cb(err);
      }
      imgFiles = [];
      for (_i = 0, _len = files.length; _i < _len; _i++) {
        f = files[_i];
        type = mime.lookup(f);
        if (type in MIME_TO_EXTESION_MAPPING && fs.statSync(f).size < 1024 * 1024 * limit) {
          imgFiles.push(f);
        }
      }
      return cb(null, imgFiles);
    });
  };

  sliceImg = function(imgFiles, limit, cb) {
    var count, filter, index, k, v, _i, _len;
    if (limit == null) {
      limit = 100;
    }
    filter = {};
    index = 1;
    count = 0;
    for (v = _i = 0, _len = imgFiles.length; _i < _len; v = ++_i) {
      k = imgFiles[v];
      if (!filter[index]) {
        filter[index] = [];
      }
      count += fs.statSync(k).size;
      if (count < 1024 * 1024 * limit) {
        filter[index].push(k);
      } else {
        index += 1;
        if (fs.statSync(k).size < 1024 * 1024 * limit) {
          filter[index] = [];
          filter[index].push(k);
          count = fs.statSync(k).size;
        }
      }
    }
    return cb(filter);
  };

  createEmailNote = function(filter) {
    var i, k, mailOption, tmp, v, _i, _len, _results;
    _results = [];
    for (k in filter) {
      v = filter[k];
      mailOption = {
        from: 'yuankui',
        to: 'shasha',
        subject: k,
        attachments: []
      };
      for (_i = 0, _len = v.length; _i < _len; _i++) {
        i = v[_i];
        tmp = {};
        tmp.filename = i;
        tmp.path = i;
        mailOption.attachments.push(tmp);
      }
      _results.push(email.sendMail(mailOption, function(err, info) {
        if (err) {
          return console.log(err);
        }
        return console.log(info);
      }));
    }
    return _results;
  };

  creatImportNote = function(filter) {
    var ENEM, enex, i, k, t, tmp, v, _i, _j, _k, _len, _len1, _len2;
    for (k in filter) {
      v = filter[k];
      tmp = [];
      ENEM = '';
      for (_i = 0, _len = v.length; _i < _len; _i++) {
        i = v[_i];
        readImg(i, function(res) {
          return tmp.push(res);
        });
      }
      for (_j = 0, _len1 = tmp.length; _j < _len1; _j++) {
        t = tmp[_j];
        ENEM += ENEM_HEAD + '<div><en-media style="height: auto;" type="' + t.mime + '" hash="' + createHashHex(t.image) + '"/></div>';
      }
      ENEM += ENEM_END;
      for (_k = 0, _len2 = tmp.length; _k < _len2; _k++) {
        t = tmp[_k];
        ENEM += ENEM_RES_HEAD + t.data.bodyHash + createENEM_RES_END(t);
      }
      ENEM += "</note></en-export>";
      enex = fs.createWriteStream(k + '.enex');
      enex.write(ENEM);
    }
    return console.log("all do");
  };

  createHashHex = function(body) {
    var hashHex, md5;
    md5 = crypto.createHash('md5');
    md5.update(body);
    hashHex = md5.digest('hex');
    return hashHex;
  };

  readImg = function(img, cb) {
    var data, hash, image, resource;
    image = fs.readFileSync(img);
    hash = image.toString('base64');
    data = new Evernote.Data();
    data.size = image.length;
    data.bodyHash = hash;
    data.body = image;
    resource = new Evernote.Resource();
    resource.mime = mime.lookup(img);
    resource.data = data;
    resource.name = img;
    resource.image = image;
    return cb(resource);
  };

  shell = function(limit) {
    if (limit == null) {
      limit = 100;
    }
    return async.auto({
      getImg: function(cb) {
        return filterImg(limit, function(err, res) {
          if (err) {
            return console.log(err);
          }
          return cb(null, res);
        });
      },
      filter: [
        'getImg', function(cb, result) {
          var imgs;
          console.log("limit");
          imgs = result.getImg;
          return sliceImg(imgs, limit, function(filter) {
            return cb(null, filter);
          });
        }
      ],
      copFile: [
        'filter', function(cb, result) {
          var filter, i, k, v, _i, _len;
          filter = result.filter;
          console.log(filter);
          for (k in filter) {
            v = filter[k];
            for (_i = 0, _len = v.length; _i < _len; _i++) {
              i = v[_i];
              if (fs.existsSync(k)) {
                fse.copySync(i, k + '/' + i);
              } else {
                fs.mkdirSync(k);
                fse.copySync(i, k + '/' + i);
              }
            }
          }
          return console.log("ok");
        }
      ],
      cImportNote: [
        'filter', function(cb, result) {
          var filter;
          filter = result.filter;
          return creatImportNote(filter);
        }
      ]
    });
  };

  if (argv.l) {
    limit = argv.l;
    shell(limit);
  } else {
    shell();
  }

  createRes = function(imgFiles, cb) {
    var resources;
    resources = [];
    return async.eachSeries(imgFiles, function(item, callback) {
      var data, hash, image, resource;
      image = fs.readFileSync(item);
      hash = image.toString('base64');
      data = new Evernote.Data();
      data.size = image.length;
      data.bodyHash = "hash";
      data.body = "image";
      resource = new Evernote.Resource();
      resource.mime = mime.lookup(item);
      resource.data = data;
      resources.push(resource);
      return callback();
    }, function(eachErr) {
      if (eachErr) {
        return cb(eachErr);
      }
    });
  };

}).call(this);

//# sourceMappingURL=app.js.map
